POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video teste 3",
    "description": "Esse é o vídeo teste 3",
    "duration": 180
}

###

GET http://localhost:3333/videos?search=node

###

PUT http://localhost:3333/videos/2adc73db-305f-4708-b0c5-3b11097243b3
Content-Type: application/json

{
    "title": "Video alterado",
    "description": "Esse vídeo foi alterado",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/2adc73db-305f-4708-b0c5-3b11097243b3
